### ISSUE TITLE
[DOXIATOOLS-3] Link checker not handling anchors very well (e.g. ignores id attribute when linking to any HTML element, too sensitive on whitespace and quotes) plus no anchor support in OnlineHTTPLinkValidator at all

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-linkcheck#13]
**[James Strachan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstrachan)** opened **[DOXIATOOLS-3](https://issues.apache.org/jira/browse/DOXIATOOLS-3?redirect=false)** and commented

have a local fix with test cases; about to try commit or will add as a patch shortly...

---

**Affects:** doxia-linkcheck-1.1

**Attachments:**
- [DOXIA-410.patch](https://issues.apache.org/jira/secure/attachment/12715687/DOXIA-410.patch) (_12.17 kB_)

**Comment by jira-importer** [comment]
**[James Strachan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstrachan)** commented

turns out I'm no longer a maven committer; so attaching a patch...

**Comment by jira-importer** [comment]
**[James Strachan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstrachan)** commented

Applied my patch to this fork...
http://github.com/jstrachan/maven-doxia-tools/commit/d55940f46eba6a30a6fe7581366a961b6067b245

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

I'm getting the following Exception:

```
 
[ERROR]FATAL ERROR
------------------------------------------------------------------------
Unclosed character class near index 82
(name|id)\s*=\s*('|")assertEqualArrays(java.lang.Object[], java.lang.Object[])('|")
                                                                                  ^
------------------------------------------------------------------------
[DEBUG]Trace
java.util.regex.PatternSyntaxException: Unclosed character class near index 82
(name|id)\s*=\s*('|")assertEqualArrays(java.lang.Object[], java.lang.Object[])('|")
                                                                                  ^
        at java.util.regex.Pattern.error(Pattern.java:1713)
        at java.util.regex.Pattern.clazz(Pattern.java:2254)
        at java.util.regex.Pattern.clazz(Pattern.java:2210)
        at java.util.regex.Pattern.sequence(Pattern.java:1818)
        at java.util.regex.Pattern.expr(Pattern.java:1752)
        at java.util.regex.Pattern.group0(Pattern.java:2530)
        at java.util.regex.Pattern.sequence(Pattern.java:1806)
        at java.util.regex.Pattern.expr(Pattern.java:1752)
        at java.util.regex.Pattern.compile(Pattern.java:1460)
        at java.util.regex.Pattern.<init>(Pattern.java:1133)
        at java.util.regex.Pattern.compile(Pattern.java:823)
        at org.apache.maven.doxia.linkcheck.validation.Anchors.matchesAnchor(Anchors.java:37)
        at org.apache.maven.doxia.linkcheck.validation.FileLinkValidator.getFile(FileLinkValidator.java:122)
        at org.apache.maven.doxia.linkcheck.validation.FileLinkValidator.getResourceKey(FileLinkValidator.java:84)
        at org.apache.maven.doxia.linkcheck.validation.LinkValidatorManager.getCachedResult(LinkValidatorManager.java:360)
        at org.apache.maven.doxia.linkcheck.validation.LinkValidatorManager.validateLink(LinkValidatorManager.java:123)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.check(DefaultLinkCheck.java:558)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.findAndCheckFiles(DefaultLinkCheck.java:480)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.findAndCheckFiles(DefaultLinkCheck.java:439)
        at org.apache.maven.doxia.linkcheck.DefaultLinkCheck.execute(DefaultLinkCheck.java:241)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.executeLinkCheck(LinkcheckReport.java:512)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.execute(LinkcheckReport.java:412)
        at org.apache.maven.plugins.linkcheck.LinkcheckReport.executeReport(LinkcheckReport.java:452)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:93)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:164)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:330)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:158)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:120)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

because of some links to javadoc methods that contain brackets. This clashes with the regexp pattern you use. Even though an id containing brackets is not a legal doxia id, we have to include the javadoc case (compare DOXIA-397).

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Patch applied with minor modifs in [r1030039](http://svn.apache.org/viewvc?rev=1030039&view=rev). Thanks!
